### ISSUE TITLE
Is it possible to highlight lines one by one?

### ISSUE THREAD

**Issue by KnockOutEZ** [yermolim/ts-pdf#10]
I want to generate the coordinates of each line so I can use them in the Highlight annotation.
I want to iterate one after another line and highlight them. How can I achieve this?

I also wanna add another question which is, can I trigger a function on line click? For example I click on line 100 in whole pdf, and it triggers a function returning 100 (The index of the line in whole pdf).

**Comment by yermolim** [comment]
I'm sorry for the late response. I have been quite busy with my main job and some personal business recently.

I do not suppose the implementation to be straightforward as of now the module doesn't track separate lines. Apart from that, I think this requirement is quite a specific one, so I'm sure that implementing this will have additional value for most of the users. Hence, for now, I'm closing this one as "not planned".

I may look at it if I have time, I can't promise anything though.
If it's still relevant for you and you have questions, feel free to contact me in private.
