### ISSUE TITLE
IOS Apply is mirrored

### ISSUE THREAD

**Issue by Niki2k1** [yermolim/ts-pdf#12]
The preview on IOS is fixed now with the new Matrix. But when applying the drawings, they are being mirrored again.

https://github.com/yermolim/ts-pdf/assets/31246997/61f3b259-e8ff-4b59-9679-8d937c4d5057

**Comment by yermolim** [comment]
Sorry for the late response. I would have fixed it if I had an Apple device to test it. I'll try to look into it next week if I find any free tools to test the web page hosted on localhost. If you have any hints, your advice is welcome.

**Comment by Niki2k1** [comment]
Hey, maybe you can make use of https://playwright.dev/ I don't know if you can launch a webkit browser but you can run tests. I have used Browserstack for testing safarionce  and they offer a free version for open source projects: https://www.browserstack.com/open-source maybe that could help you test it. If not I can also try to debug it and make a PR

**Comment by yermolim** [comment]
Mirrored annotations should be fixed now. At least, they are displayed as they should during testing with https://www.lambdatest.com/
If the issue persists or some annotations are still displayed incorrectly, feel free to re-open the issue.
