### ISSUE TITLE
demo doesn't run

### ISSUE THREAD

**Issue by sublimz** [yermolim/ts-pdf#15]
Hello,

I am trying to run the demo but something it's wrong; any advises ?

root@DESKTOP-Q4N3TRN:/opt# git clone https://github.com/yermolim/ts-pdf.git
Cloning into 'ts-pdf'...
remote: Enumerating objects: 8912, done.
remote: Counting objects: 100% (131/131), done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 8912 (delta 81), reused 99 (delta 77), pack-reused 8781
Receiving objects: 100% (8912/8912), 29.57 MiB | 918.00 KiB/s, done.
Resolving deltas: 100% (6949/6949), done.
root@DESKTOP-Q4N3TRN:/opt# cd ts-pdf/
root@DESKTOP-Q4N3TRN:/opt/ts-pdf# npm run start

> ts-pdf@0.11.3 start
> npm run build && lite-server -c ls-config.json

> ts-pdf@0.11.3 build
> npm run buildts && npm run buildru && npm run copypdfjsworker

> ts-pdf@0.11.3 buildts
> tsc && npm run copypngtotsc

sh: 1: tsc: not found
root@DESKTOP-Q4N3TRN:/opt/ts-pdf#

Thx

**Comment by yermolim** [comment]
Hello. It looks like you missed installing the npm packages before starting the demo using 'npm install'.
