### ISSUE TITLE
Import to Obsidian plugin and usage ?

### ISSUE THREAD

**Issue by 1811htsang** [yermolim/ts-pdf#17]
Hi, i recently find out ur library for pdf feature, so at first i imported it successfully to code for obsidian plugin. However, i've encountered a problem about this 
```const options: TsPdfViewerOptions = {
    containerSelector: "#your-html-container-selector", 
    workerSource: "", // path to the PDF.js worker script
    userName: "your_username",
    // you can check other properties using your editor hints
 };
```
i quite confused about the `containerSelector` and `workerSource` , which parameter of obsidian that i can fill it in, i've already installed pdfjs library for it

**Comment by jacobdavis1** [comment]
Hello! I am not the developer, just someone who is using their good work.

Worker source is the actual worker file, eg a file path or a CDN (web-hosted js file): https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.16.105/pdf.worker.min.js

Container selector is the CSS selector to find the element that will become the host for the PDF Viewer. Set the ID property for the HTML element you want targeted and then set the containerSelector to "#the-id-you-chose" (# means it looks at IDs). Be aware that this library makes the targeted element a Shadow DOM host.

As for your use case with Obsidian, I am afraid I dont know much about that. If it has an HTML structure and a DOM, I dont see why it wouldnt work.

**Comment by yermolim** [comment]
I'm sorry, but I never worked with Obsidian, so I can't provide any answers specific to that app and it's plugins. 
As for the parameters, the comment above explains them pretty well.
