### ISSUE TITLE
ink color

### ISSUE THREAD

**Issue by nufanDK** [yermolim/ts-pdf#18]
I have forked your project, to add some more styling parameters, and I would also like to be able to change the color of the ink strokes, but I cannot seem to find where to set this color.
Can you give a pointer? :-)

**Comment by nufanDK** [comment]
Classical. Ask the question, and then the answer comes. 
Found it finally in the annotatorservice :-)

Another thing though: a color picker. 
I believe that it looks like it builds it, but I don't have a picker in the ui.

**Comment by yermolim** [comment]
I'm sorry for the late answer. I'm afraid it's no longer relevant for the author of the issue. However, in case anyone else has the same question: the color picker replaces the default context menu when the ink annotation tool is active. I should add some tooltips for that.
