### ISSUE TITLE
How to adjust the zoom factor

### ISSUE THREAD

**Issue by gaoxingzaq** [yermolim/ts-pdf#2]
How to adjust the zoom factor? I want to adjust it to 3000 times. How to customize the signature and seal, and the signature and seal. Upload and signature do not work

**Comment by yermolim** [comment]
You can adjust min and max scale values via TsPdfViewerOptions corresponding properties. As for changing the scaling step - it's not implemented yet. I'll do it later.

About your other problems - you should provide more information: error messages, screenshots, code examples, problem description. Unfortunately, 'do not work' has no useful information in it. I'm closing this issue. If you are ready to describe your problem in more detail, just open a new issue.
