### ISSUE TITLE
Upgrade pdf.js

### ISSUE THREAD

**Issue by onsquareDev** [yermolim/ts-pdf#20]
ts-pdf uses "pdfjs-dist": "^2.16.105". This version have a security vulnerability:

https://github.com/advisories/GHSA-wgrm-67xf-hhpq

Please update it to 4.2.67 or later.

**Comment by yermolim** [comment]
I'll look into it if/when I have time. The update is not straightforward as they removed the piece of functionality which is used for text selection. I need to come up with a new approach to keep the text annotation functionality.

**Comment by yermolim** [comment]
Done

**Comment by pocorall** [comment]
Great, thanks!
