### ISSUE TITLE
I hope ts-pdf can enable different users to only operate their own annotations.

### ISSUE THREAD

**Issue by yingming77** [yermolim/ts-pdf#22]
1、a annotation has a author. so I hope ts-pdf can enable different users to only operate their own annotations.
2、How to create a watermark using the author's name in ts-pdf

**Comment by yermolim** [comment]
1. There is no built-in functionality for that. I'll consider adding it if I have time. The implementation should be pretty straightforward. I can't promise that it'll be soon though. 
2. There is no watermark-related functionality present in this module. The closest you can get is to generate a watermark image in any available third-party software and add it to the file as stamps. It should suffice for printing. However, the stamps are easily removable in any software which allows you to edit the annotations. The proper way is to add watermarks as images but it's not implemented in td-pdf. It's a good idea for a feature though.
