### ISSUE TITLE
vue3-ts项目报错

### ISSUE THREAD

**Issue by shenxiang216** [yermolim/ts-pdf#3]
error  in ./node_modules/pdfjs-dist/build/pdf.js

Module parse failed: Unexpected token (2267:39)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
|   async getXfa() {
>     return this._transport._htmlForXfa?.children[this._pageIndex] || null;
|   }
|

 @ ./node_modules/ts-pdf/dist/ts-pdf.esm.js 51:0-108 627:31-46 26611:37-64 29960:39-50 31212:8-27  
 @ ./node_modules/cache-loader/dist/cjs.js??ref--14-0!./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--14-2!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/components/Pdf.vue?vue&type=script&lang=ts
 @ ./src/components/Pdf.vue?vue&type=script&lang=ts
 @ ./src/components/Pdf.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--14-0!./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--14-2!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/views/Books.vue?vue&type=script&lang=ts
 @ ./src/views/Books.vue?vue&type=script&lang=ts
 @ ./src/views/Books.vue
 @ ./src/router/index.ts
 @ ./src/main.ts
 @ multi ./node_modules/@vue/cli-service/node_modules/webpack-dev-server/client?http://192.168.114.11:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts

**Comment by LibertyNLP** [comment]
Hi , I wish my work can help you.
I have figured out a solution of pdf.js annotation, use only pdf.js dist, and it is very easy to import into your project.

Demo and source code: https://demos.libertynlp.com/#/pdfjs-annotation
Demo video:https://www.youtube.com/watch?v=IYD7WKzx-yc&t=3s

functions:
① highlight : highlight selected text;
② underline : underline selected text;
③ edit: edit annotation ( copy/delete/add comment/navigate );
④ output annotations : output annotations for importing;
⑤ import annotations : import annotations for current file;
⑥ download annotations : download annotations and comments text;
⑦ undo annotations : undo annotations in current page;
⑧ help : open help file;

**Comment by yermolim** [comment]
https://github.com/mozilla/pdf.js/issues/13200
