### ISSUE TITLE
批注不支持中文

### ISSUE THREAD

**Issue by cshenger** [yermolim/ts-pdf#5]
这个批注只能写英文不能写中文，且很多编辑的地方存在只能输入文字不能删除文字的问题
![image](https://user-images.githubusercontent.com/5855865/168704387-ee469b25-7932-4db4-b967-64088486414b.png)

**Comment by LibertyNLP** [comment]
Hi , I wish my work can help you.
I have figured out a solution of pdf.js annotation, use only pdf.js dist, and it is very easy to import into your project.

Demo and source code: https://demos.libertynlp.com/#/pdfjs-annotation
Demo video:https://www.youtube.com/watch?v=IYD7WKzx-yc&t=3s

functions:
① highlight : highlight selected text;
② underline : underline selected text;
③ edit: edit annotation ( copy/delete/add comment/navigate );
④ output annotations : output annotations for importing;
⑤ import annotations : import annotations for current file;
⑥ download annotations : download annotations and comments text;
⑦ undo annotations : undo annotations in current page;
⑧ help : open help file;

**Comment by yermolim** [comment]
It looks like there are problems with encoding. Sorry, but I do not plan to support Chinese. About the problem with deleting text, I can say nothing without the problem details. But you posted this long ago, so I doubt it's relevant for you. But if you are still interested, you can always open a new issue and provide more information about the problem.
